#include "web_page.hpp"

const uint8_t index_page[] =
"<!DOCTYPE html>\n"
"<html xmlns=\"http://www.w3.org/1999/xhtml\">\n"
"<head>\n"
"<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n"
"<title>Firmware Upgrade</title>\n"
"<script type=\"text/javascript\">\n"
"function UpGrade() {\n"
"    if (document.FirmWareUpgrade.file.value == \"\") {\n"
"        alert(\"No file!\");\n"
"        return;\n"
"    }\n"
"    if (confirm('Update?')) {\n"
"        document.FirmWareUpgrade.submit();\n"
"    }\n"
"}\n"
"</script>\n"
"</head>\n"
"<body>\n"
"<h2 align=\"center\">Firmware Upload</h2>\n"
"<form action=\"update_firmware.cgi\" method=\"post\" enctype=\"multipart/form-data\" name=\"FirmWareUpgrade\">\n"
"    <p align=\"center\">\n"
"        <input type=\"file\" name=\"file\" />\n"
"        <input type=\"button\" value=\"Upgrade\" onclick=\"UpGrade()\" />\n"
"    </p>\n"
"</form>\n"
"</body>\n"
"</html>\n";
